---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: retrospekt
  labels:
    name: retrospekt

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrospekt-backend
  namespace: retrospekt
  labels:
    app: retrospekt-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retrospekt-backend
  template:
    metadata:
      labels:
        app: retrospekt-backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: backend
          image: ghcr.io/stevendejongnl/retrospekt-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: retrospekt-mongodb-secret
                  key: mongodb-url
            - name: MONGODB_DATABASE
              value: "retrospekt_production"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: retrospekt-backend
  namespace: retrospekt
spec:
  selector:
    app: retrospekt-backend
  ports:
    - name: http
      port: 8000
      targetPort: http

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrospekt-frontend
  namespace: retrospekt
  labels:
    app: retrospekt-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retrospekt-frontend
  template:
    metadata:
      labels:
        app: retrospekt-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/stevendejongnl/retrospekt-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: retrospekt-frontend
  namespace: retrospekt
spec:
  selector:
    app: retrospekt-frontend
  ports:
    - name: http
      port: 80
      targetPort: http

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retrospekt
  namespace: retrospekt
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - retrospekt.steven-dejong.nl
      secretName: retrospekt-tls
  rules:
    - host: retrospekt.steven-dejong.nl
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: retrospekt-backend
                port:
                  name: http
          - path: /health
            pathType: Exact
            backend:
              service:
                name: retrospekt-backend
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retrospekt-frontend
                port:
                  name: http
