import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'

// Works whether tsx runs from CJS or ESM context
const scriptsDir = resolve(process.cwd(), 'scripts')
const repoRoot = resolve(process.cwd(), '..')
const changelogPath = resolve(repoRoot, 'CHANGELOG.md')
const outputPath = resolve(process.cwd(), 'src/generated/changelog.ts')
void scriptsDir

type Kind = 'Features' | 'Fixes' | 'Refactor' | 'Docs' | 'Other'

interface ChangelogItem {
  scope?: string
  text: string
}

interface ChangelogGroup {
  kind: Kind
  items: ChangelogItem[]
}

export interface ChangelogEntry {
  version: string
  date: string
  groups: ChangelogGroup[]
  highlight?: { title: string; body: string }
}

const SECTION_MAP: Record<string, Kind> = {
  'features': 'Features',
  'feature': 'Features',
  'bug fixes': 'Fixes',
  'bug fix': 'Fixes',
  'fixes': 'Fixes',
  'refactor': 'Refactor',
  'refactoring': 'Refactor',
  'documentation': 'Docs',
  'docs': 'Docs',
  'performance improvements': 'Other',
  'chore': 'Other',
  'style': 'Other',
  'tests': 'Other',
}

function parseChangelog(content: string): ChangelogEntry[] {
  const entries: ChangelogEntry[] = []
  // Split on version headings: ## [x.y.z]
  const blocks = content.split(/^(?=## \[)/m).filter((b) => b.trim())

  for (const block of blocks) {
    const lines = block.split('\n')
    const headerLine = lines[0]
    const versionMatch = headerLine.match(/^## \[(\d+\.\d+\.\d+)\].*\((\d{4}-\d{2}-\d{2})\)/)
    if (!versionMatch) continue

    const version = versionMatch[1]
    const date = versionMatch[2]
    const groups: ChangelogGroup[] = []
    let currentKind: Kind | null = null
    let currentItems: ChangelogItem[] = []

    for (let i = 1; i < lines.length; i++) {
      const line = lines[i]
      const sectionMatch = line.match(/^### (.+)/)
      if (sectionMatch) {
        if (currentKind && currentItems.length > 0) {
          groups.push({ kind: currentKind, items: currentItems })
        }
        currentKind = SECTION_MAP[sectionMatch[1].toLowerCase()] ?? 'Other'
        currentItems = []
        continue
      }

      const itemMatch = line.match(/^\* \*\*(.+?):\*\* (.+?)(?:\s+\(\[[\da-f]+\].+)?$/)
      if (itemMatch && currentKind) {
        currentItems.push({ scope: itemMatch[1], text: itemMatch[2] })
        continue
      }

      const plainItemMatch = line.match(/^\* (.+?)(?:\s+\(\[[\da-f]+\].+)?$/)
      if (plainItemMatch && currentKind) {
        currentItems.push({ text: plainItemMatch[1] })
      }
    }

    if (currentKind && currentItems.length > 0) {
      groups.push({ kind: currentKind, items: currentItems })
    }

    if (groups.length > 0) {
      entries.push({ version, date, groups })
    }
  }

  return entries
}

function loadHighlights(): Record<string, { title: string; body: string }> {
  try {
    const highlightsPath = resolve(process.cwd(), 'src/changelog-highlights.ts')
    const src = readFileSync(highlightsPath, 'utf-8')
    // Extract the object literal — eval-free: use JSON5-like extraction
    const match = src.match(/export const CHANGELOG_HIGHLIGHTS[^=]*=\s*(\{[\s\S]*?\}) as const/)
    if (!match) return {}
    // Replace single-quoted strings and trailing commas for JSON parsing
    const jsonStr = match[1]
      .replace(/'/g, '"')
      .replace(/,\s*\}/g, '}')
      .replace(/,\s*\]/g, ']')
    return JSON.parse(jsonStr) as Record<string, { title: string; body: string }>
  } catch {
    return {}
  }
}

export function generateChangelog(): void {
  const content = readFileSync(changelogPath, 'utf-8')
  const entries = parseChangelog(content)
  const highlights = loadHighlights()

  const enriched = entries.map((entry, idx) => ({
    ...entry,
    highlight: highlights[entry.version] ?? (idx === 0
      ? { title: `What's new in v${entry.version}`, body: entry.groups[0]?.items[0]?.text ?? '' }
      : undefined),
  }))

  mkdirSync(dirname(outputPath), { recursive: true })

  const code = [
    '// Auto-generated by scripts/parse-changelog.ts — do not edit',
    '',
    "export type ChangelogKind = 'Features' | 'Fixes' | 'Refactor' | 'Docs' | 'Other'",
    '',
    'export interface ChangelogItem { scope?: string; text: string }',
    'export interface ChangelogGroup { kind: ChangelogKind; items: ChangelogItem[] }',
    'export interface ChangelogEntry {',
    '  version: string',
    '  date: string',
    '  groups: ChangelogGroup[]',
    '  highlight?: { title: string; body: string }',
    '}',
    '',
    `export const CHANGELOG: ChangelogEntry[] = ${JSON.stringify(enriched, null, 2)}`,
  ].join('\n')

  writeFileSync(outputPath, code, 'utf-8')
  console.log(`[parse-changelog] wrote ${enriched.length} entries → src/generated/changelog.ts`)
}

generateChangelog()
